Remove mobile view resolution and the mark_desktop_only skip reason in tests
mozilla/addons-release-tests pull request #105
Opened 2021-02-04 15:49 UTC by AlexandraMoga

Fix #97

2021-02-04 17:12 UTC, jrbenny35 requested changes
Looks good, just some styling comments

2021-02-04 17:12 UTC, jrbenny35 commented on test_search.py
> -
These spaces should still be here. See, https://www.python.org/dev/peps/pep-0008/#imports

2021-02-04 17:12 UTC, jrbenny35 commented on test_search.py
> -
These spaces should still be here. See, https://www.python.org/dev/peps/pep-0008/#imports

2021-02-04 17:12 UTC, jrbenny35 commented on conftest.py
> -
These spaces should still be here. See, https://www.python.org/dev/peps/pep-0008/#imports

2021-02-05 12:31 UTC, AlexandraMoga commented
While updating the the files included in the initial patch, I've noticed that a few other files needed the same reorganization, so I've updated those too, although they were not in the initial scope of this patch.

2021-02-05 15:06 UTC, jrbenny35 commented
> 
> 
> While updating the the files included in the initial patch, I've noticed that a few other files needed the same reorganization, so I've updated those too, although they were not in the initial scope of this patch.

This time no biggie, but lets file an issue for things like this next time 😃

2021-02-05 15:11 UTC, jrbenny35 approved these changes

2021-02-05 15:11 UTC, merged