Improvements to the circleci config file
mozilla/addons-release-tests pull request #16
Opened 2020-11-06 15:14 UTC by AlexandraMoga

A new attempt at setting up CircleCi. Hope this works now.

2020-11-12 21:09 UTC, jrbenny35 commented
I think since the build is successful we should just change this PR to allow for all the tests to run.

2020-11-12 21:10 UTC, jrbenny35 requested changes
Awesome work!

2020-11-12 21:10 UTC, jrbenny35 commented on .circleci/config.yml
>    build:
Can we name this ```test``` instead? `

2020-11-17 15:48 UTC, AlexandraMoga commented on .circleci/config.yml
>    build:
renamed as `test`

2020-11-17 16:54 UTC, jrbenny35 approved these changes
r+, wc

Looks great! Added some final requests but once you address them you can merge.

2020-11-17 16:54 UTC, jrbenny35 commented on test_login.py
> +@pytest.mark.skip
Can we add a reason here, just so we remember why we skipped. https://docs.pytest.org/en/latest/skipping.html#skipping-test-functions

2020-11-17 16:54 UTC, jrbenny35 commented on test_login.py
> +@pytest.mark.skip
Can we add a reason here, just so we remember why we skipped. https://docs.pytest.org/en/latest/skipping.html#skipping-test-functions

2020-11-18 16:04 UTC, merged