Ratings tests
mozilla/addons-release-tests pull request #245
Opened 2021-07-16 12:44 UTC by AlexandraMoga

These are a set of tests that are covering the Ratings card from the add-on detail page. They cover writing, editing, deleting reviews and some other related functionalities. These tests need to be run serially, since they are interdependent.

I need to change the CircleCI config to allow for parallel and serial test runs to work separately, due to an incompatibility between `pytest-xdist` and `pytest-depends` (which I need for the ratings tests, as some tests are interdependent). `pytest-xdist` will simply skip a test if its dependency has not run yet.

So far this has been a failure. I can't figure out why CircleCI remains stuck in the 'Run serial tests' step. It should exit and proceed to the next step once all the tests have been executed. @jrbenny35 maybe you can see something I don't in the config file? This is from the last run - https://app.circleci.com/pipelines/github/mozilla/addons-release-tests/577/workflows/1d110e7d-a1e5-43de-9cab-05ccf73096cd/jobs/615. I've manually cancelled the job as it would not finish.

I'll also need to investigate further why some ratings tests are failing on CI, since I could not reproduce those errors locally.

2021-08-05 07:37 UTC, AlexandraMoga commented
Tests are passing with the latest version of `pytest-xdist`. @jrbenny35  I think this PR is ready for a proper review. Thanks for the help.

2021-08-05 16:03 UTC, jrbenny35 requested changes
R+ just some nits

2021-08-05 16:03 UTC, jrbenny35 commented on pages/desktop/details.py
> +        def delete_confirm_button(self):
maybe this should have click in the name. This seems like it is named like a property not a function.
```suggestion
        def click_delete_confirm_button(self):
```

2021-08-05 16:03 UTC, jrbenny35 commented on pages/desktop/details.py
> +        def report_abuse(self):
This should also have click in the name.
```suggestion
        def click_report_abuse_button(self):
```

2021-08-06 09:40 UTC, AlexandraMoga commented on .circleci/config.yml
> +          name: Run serial tests
I've modified the circleci config to run the tests in parallel jobs. Please have a look and let me know what you think.

2021-08-06 13:55 UTC, jrbenny35 approved these changes

2021-08-06 13:55 UTC, jrbenny35 commented on .circleci/config.yml
> +      - parallel_tests
WOOOOOOOOOOOOOOO

2021-08-06 13:55 UTC, merged