Part one: add wait messages in some of our pages
mozilla/addons-release-tests pull request #299
Opened 2021-09-17 13:45 UTC by AlexandraMoga

I've started adding wait messages in the following pages:

- `pages/desktop/base.py`
- `pages/desktop/login.py`
- `pages/desktop/reviews.py`
- `pages/desktop/search.py`

I didn't want to have a huge patch, so the other pages will be handled in other patches.

I've also tweaked the waits in two functions:  `pages/desktop/base.py - logged_in` and `pages/desktop/reviews.py - click_reply_to_review`

2021-09-21 15:28 UTC, jrbenny35 requested changes
Love these, will help debugging for sure!

2021-09-21 15:28 UTC, jrbenny35 commented on pages/desktop/base.py
> +                print(f'{exception}: Trying to find the element again')
Should this be "Try to find the element again"?

2021-09-21 15:28 UTC, jrbenny35 commented on pages/desktop/base.py
> +            message=f'Number of windows was {len(self.selenium.window_handles)}',
could we add an "expected 2" at the end of this?
```suggestion
            message=f'Number of windows was {len(self.selenium.window_handles)}, expected 2',
```

2021-09-21 15:28 UTC, jrbenny35 commented on pages/desktop/base.py
> +            message=f'Number of windows was {len(self.selenium.window_handles)}',
could we add an "expected 2" at the end of this?
```suggestion
            message=f'Number of windows was {len(self.selenium.window_handles)}, expected 2',
```

2021-09-21 15:28 UTC, jrbenny35 commented on pages/desktop/base.py
> +            EC.title_contains(term), message=f'Page title was {self.selenium.title}'
```suggestion
            EC.title_contains(term), message=f'Page title was {self.selenium.title}, expected{term}.'
```

Thoughts?

2021-09-22 08:20 UTC, AlexandraMoga commented
Change requests solved. I'm merging this PR because I need those debug messages up and running.

2021-09-22 08:20 UTC, merged